### ISSUE TITLE
is it possible to get a random poem?

### ISSUE THREAD

**Issue by MarsVard** [thundercomb/poetrydb#1]
I would like to use this api to get a random poem.

**Comment by thundercomb** [comment]
Yes it would be quite easy in most programming languages. This gist shows how it can be done in ruby. Let me know if anything is unclear.

https://gist.github.com/thundercomb/4f23c3a1de0f54c7bf7e

**Comment by MarsVard** [comment]
awesome! thank you.

**Comment by thundercomb** [comment]
Hi @MarsVard 

In case this is still of interest, it is now possible to get an individual random poem by calling the `/random` endpoint.

It is also possible to combine this with other searches, for example to return three random poems by Emily Dickinson:

`/author,random/Emily Dickinson;3`

or to return 5 random sonnets:

`/title,random/Sonnet;5`

and specifying output fields:

`/title,random/Sonnet;5/title,author,lines.text`

See also issues #19 and #27
