### ISSUE TITLE
API AJAX Call

### ISSUE THREAD

**Issue by thecodingaviator** [thundercomb/poetrydb#10]
Guys I'm calling the API like this:
`$(document).ready(function() {
  $("#submit").click(function(event) {
    var poet = $("#poet").val();
    var title = $("#title").val();
    var reppoet = poet.replace(" ", "%20");
    var reptitle = title.replace(" ", "%20");
    var url = <es6backtick>http://poetrydb.org/title,author/${reptitle};${reppoet}/author,title,linecount,lines.json</es6backtick>;
    $.ajax({
      type: 'GET',
      url: url,
      success: function(data) {
        console.log(data);
      },
      error: function(url){
        console.log('Error!'+url);
      }
    });
  });
});
`
It always goes to error and returns
`"Error![object Object]"`

Please help me out

**Comment by thecodingaviator** [comment]
In the code the ES6 backtick is like `` only I have written that because else GitHub would mess up the code

**Comment by thundercomb** [comment]
Hi @hiparthparth 

Thanks for the query, the intended construction of the URL looks fine to me, including the substitution of the space with "%20". Does the URL logged to the console ( in this section: `console.log('Error!'+url)` ) work ok when you paste it into the address bar in the browser, or when you use curl?

Also, what does the markup es6backtick do, does it behave the same as normal string double quotes?

Have you tried returning a completely separate website with spaces in the address, and does it work ok?

For example here is a completely random one I found:

https://www.itseeze-colchester.co.uk/blog/tag=website%20design%20colchester/

Unfortunately I'm not familiar enough with Ajax to give you more specific advice, but hopefully this gives you some pointers to help you debug and troubleshoot.

**Comment by thecodingaviator** [comment]
Yup the url in `console.log('Error!'+url);` works just fine!

The es6backtick actually translates to the backtick character the one which is used to markup code in Gtihub. That's just a shortform and it is totally fine and tested.

**Comment by thecodingaviator** [comment]
@thundercomb The issue has been resolved it was due to my server not accepting http requests on an https server.

**Comment by thundercomb** [comment]
Ok thanks, great to hear you managed to resolve it.
