### ISSUE TITLE
Random Poem call in JSON/AJAX

### ISSUE THREAD

**Issue by thecodingaviator** [thundercomb/poetrydb#11]
@thundercomb Do you know what parameters should I retrieve and pass in AJAX for getting a random poem? I tried understanding the ruby one but unfortunately I don't know ruby.

**Comment by thecodingaviator** [comment]
Never mind. Did it. Thank you for the help @thundercomb

**Comment by thundercomb** [comment]
Hi @thecodingaviator 

In case this is related and of interest, it is now possible to get an individual random poem by calling the `/random` endpoint.

It is also possible to combine this with other searches, for example to return three random poems by Emily Dickinson:

`/author,random/Emily Dickinson;3`

or to return 5 random sonnets:

`/title,random/Sonnet;5`

and specifying output fields:

`/title,random/Sonnet;5/title,author,lines.text`

See also issues #19  and #27

**Comment by thecodingaviator** [comment]
@thundercomb ah, it's been so long since I did this project. Thanks for the update! :)
