### ISSUE TITLE
HTTPS API call

### ISSUE THREAD

**Issue by QAInsights** [thundercomb/poetrydb#12]
Could you please provide API in HTTPS protocol?

**Comment by tzohpilotl** [comment]
Is it possible for this to happen?

**Comment by thundercomb** [comment]
Thanks for making the suggestion and for the upvotes. Https is best practice so definitely a good idea to implement. 

The good news is that https is now available using a third party proxy (CloudFlare).

PS: Note that Heroku's own SSL offering requires a paid upgrade, which I've tried to avoid. This  also ruled out a solution on the app server side, for example a code based solution using Let's Encrypt. Fortunately CloudFlare's free service makes it quite easy to set up SSL. The only caveat is that it does mean if CloudFlare or Heroku changes their free service offering in future, this might need reviewing again.

In the meantime, https is good to go.

**Comment by thundercomb** [comment]
https is now being enforced via the proxy, and the api has been tested to behave as expected.

The issue will now be closed, but feel free to ask if there are any further questions related to this.
