### ISSUE TITLE
Contributions/posting to DB

### ISSUE THREAD

**Issue by msaminsky** [thundercomb/poetrydb#13]
Is there any way we can add or contribute to the database? There's a ton of poems I'd love to see in here!

**Comment by thundercomb** [comment]
Hi @msaminsky,

Thanks for your interest! 

Do you have any specific examples in mind?

The main constraint is copyright, so all of the poetry in Poetry DB are intended to be commons or out-of-copyright poetry. If you have access to digital poetry that fall in this category we can make a plan.

**Comment by msaminsky** [comment]
That makes a ton of sense. My suggestion would have been Mary Oliver, but I doubt that there's much in the public domain.

**Comment by Carlosarturo28** [comment]
Hi, I also would like to see latinamerican poetry and what about translating some of the poems to other languages? I would love to collaborate!

**Comment by thundercomb** [comment]
Hi @Carlosarturo28, that's a great idea - I would welcome suggestions for adding Latin American poetry. Do you have any specific poems / translations in mind?
The main criteria would be that they are in the public domain.

**Comment by owocado** [comment]
Anyway we can add the poem called The Raven by Edgar Allan Poe? Few of this author's poems are not in database.

**Comment by thundercomb** [comment]
@ow0x most poems by Edgar Allan Poe have now been added to the database, including "The Raven".
@msaminsky yes unfortunately Mary Oliver does not appear to have poetry in the public domain.

As long as the poems are in the public domain they can be added.
Will close this but feel free to open new requests for individual cases.
