### ISSUE TITLE
Limit the number of results?

### ISSUE THREAD

**Issue by jesslark** [thundercomb/poetrydb#17]
Some of my calls return a large amount of information, which is a lot to download and takes more time than is expected by most users. Is there a way to limit the number of results?

**Comment by mkbaker** [comment]
I am also interested in a solution to this problem!

**Comment by thundercomb** [comment]
Thank you @jessmear for raising this request.
The feature is now available using the `poemcount` input field and corresponding search field.

For example, to return only the first Shakespeare sonnet found, provide:

`http://poetrydb.org/author,title,poemcount/Shakespeare;Sonnet;1`

This returns:

```
[
  {
    "title": "Sonnet 1: From fairest creatures we desire increase",
    "author": "William Shakespeare",
    "lines": [
      "From fairest creatures we desire increase,",
      "That thereby beauty's rose might never die,",
      "But as the riper should by time decease,",
      "His tender heir might bear his memory:",
      "But thou contracted to thine own bright eyes,",
      "Feed'st thy light's flame with self-substantial fuel,",
      "Making a famine where abundance lies,",
      "Thy self thy foe, to thy sweet self too cruel:",
      "Thou that art now the world's fresh ornament,",
      "And only herald to the gaudy spring,",
      "Within thine own bud buriest thy content,",
      "And tender churl mak'st waste in niggarding:",
      "  Pity the world, or else this glutton be,",
      "  To eat the world's due, by the grave and thee."
    ],
    "linecount": "14"
  }
]
```
Or, to return the first five Shakespeare sonnets' titles, provide:

`http://poetrydb.org/author,title,poemcount/Shakespeare;Sonnet;5/title`

This returns:

```
[
  {
    "title": "Sonnet 1: From fairest creatures we desire increase"
  },
  {
    "title": "Sonnet 2: When forty winters shall besiege thy brow"
  },
  {
    "title": "Sonnet 3: Look in thy glass and tell the face thou viewest"
  },
  {
    "title": "Sonnet 4: Unthrifty loveliness, why dost thou spend"
  },
  {
    "title": "Sonnet 5: Those hours, that with gentle work did frame"
  }
]
```

Hope that fulfills what you were looking for.

**Comment by thundercomb** [comment]
The issue will be closed as the api can now limit the number of poems that are returned via the `poemcount` input field (and via the `random` input field for random poems - see issues #19  and #27  ).

Feel free to ask if there are any further questions regarding this.
