### ISSUE TITLE
[Feature Request] Random Endpoint

### ISSUE THREAD

**Issue by nightly** [thundercomb/poetrydb#19]
Hi,

I was wondering if there could be a simple endpoint added to gather a random poem?

Thanks!

**Comment by thundercomb** [comment]
Hi @Prolonged, thank you for the feature request. An endpoint has been added that returns a single, randomly selected poem at `/random`. Please let me know if this is what you had in mind.

I can also see the possibility for further random selection functionality, such as taking an existing search and then selecting a random poem (or poems) from that set. For example returning a random sonnet by Shakespeare: `/author,title/Shakespeare;Sonnet/random`. It is sometimes easier to implement these type of requirements on the user side though. 

Nevertheless, if you think there is a need for further random selection functionality, could you please open it as a separate issue? We can then keep this request for the case of a single random poem across all poems.

**Comment by nightly** [comment]
Thanks for the fast implementation, this is exactly what I had in mind!

**Comment by thundercomb** [comment]
You're welcome!

**Comment by thundercomb** [comment]
Hi @Prolonged 

In case this would be of interest, it is now also possible to combine `random` with other searches, for example to return three random poems by Emily Dickinson:

`/author,random/Emily Dickinson;3`

or to return 5 random sonnets:

`/title,random/Sonnet;5`

and specifying output fields:

`/title,random/Sonnet;5/title,author,lines.text`

See also issue #27
