### ISSUE TITLE
500 Internal Server Error for Swinburne "Hymn..."

### ISSUE THREAD

**Issue by sethwilsonUS** [thundercomb/poetrydb#41]
The following URL returns a 500 Internal Server Error, even though it's using the title supplied by the API:

https://poetrydb.org/title/Hymn%20to%20Proserpine%20(After%20the%20Proclamation%20of%20the%20Christian

**Comment by thundercomb** [comment]
@sethwilsonUS thank you for raising. This should now work as expected.
