### ISSUE TITLE
Missing a poem, how can we add to the dB ?

### ISSUE THREAD

**Issue by Joshuajrodrigues** [thundercomb/poetrydb#42]
Hey I used your api for a small telegram bot for a friend who likes poems, She loves Emily Dickinson and I found one of them poems she likes missing. Is there a way we can add to the database ? or maybe you can ?

https://www.poemhunter.com/poem/forbidden-fruit-a-flavor-has/

also really cool project. Many thanks😄

**Comment by thundercomb** [comment]
You're welcome.
Thanks for raising the request, I'm aiming to get to it within the coming week.

**Comment by thundercomb** [comment]
Apologies, haven't been able to find the time yet.
I should have a bit more leeway in a couple of weeks.

**Comment by thundercomb** [comment]
@Joshuajrodrigues that should be there for you now.
