### ISSUE TITLE
API Is Down

### ISSUE THREAD

**Issue by Sid-MB** [thundercomb/poetrydb#46]
Upon querying the API, or visiting poetrydb.org, the following message is displayed:

> # Application error
> An error occurred in the application and your page could not be served. If you are the application owner, [check your logs for details](https://devcenter.heroku.com/articles/logging#view-logs). 
> You can do this from the Heroku CLI with the command `heroku logs —tail`

**Comment by thundercomb** [comment]
Is this still an issue for you? All seems ok at this end.

**Comment by Sid-MB** [comment]
Seems to be rectified, thank you!
