### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by Immortalin** [thundercomb/poetrydb#5]
Out of curiosity, where is the data sourced from?

**Comment by thundercomb** [comment]
The data was extracted from a variety of publicly available sources of poetry on the internet - a considerable number are from texts on gutenberg.org and most of the rest from poetry websites. All are considered out-of-copyright, so no "modern" poetry is included.

**Comment by Immortalin** [comment]
@thundercomb can you add those of Robert Frost and Anthony Munday?

**Comment by thundercomb** [comment]
Unfortunately most of Robert Frost's poetry is under copyright, and the Frost Estate does not grant permission to use his works very easily.
With regards to Anthony Munday (1560 - 1633) very few poems appear to be extant in text form on the internet. Do you know any reliable sources?
