### ISSUE TITLE
Is there any way to explicitly limit the number of poems returned?

### ISSUE THREAD

**Issue by javogel** [thundercomb/poetrydb#7]

**Comment by thundercomb** [comment]
Hi @javogel, 
no there isn't a way to do this at the moment.
In what context would this be useful from a user's perspective?

**Comment by javogel** [comment]
Hi @thundercomb, 

So, im building an Alexa skill that allows Alexa to recite random poems and also poems based on a specific search query. Im using poetrydb for this, which I love, btw. so thank you!

Right now Im having some issues with the response time when searching for a topic. For example If a user wants a poem about "love" (or at least it that includes the word) , then I would build the following url to make a request: 

http://poetrydb.org/lines/love/title,author,lines     

This takes too long for my needs. However, all I need is 1 poem that matches. And when I ask if there is a way to limit the number of poems in response, im assuming that by doing so, the response time might be quicker.

Right now I partially solved the problem by adding a linecount parameter (which I make a random number from 10-30, for example) to the url:

http://poetrydb.org/lines,linecount/love;12/lines,author,title   (For Example)

and this ends up in a shorter response time that is within the acceptable time to render the response.

Any help or ideas would be appreciated. Thank you, again!

**Comment by thundercomb** [comment]
Hi @javogel,

I tested it myself and can see the result would be quite slow if you only wanted the first poem. This is largely because it returns all the data in the lines field, which makes up the bulk of the query data. You can reduce the time significantly by first querying:

http://poetrydb.org/lines/love/title

Then pick a title query directly on the title, for example:

http://poetrydb.org/title/I%20Have%20A%20Rendezvous%20With%20Death/lines,author,title 

I imagine that picking a random title would be more useful than always picking the first title, as the returned poem for a given search term would then always be something new and different. In any case, that is up to you.

Let me know if that helps.

**Comment by javogel** [comment]
the proposed solution works perfectly. Thank you very much, @thundercomb! Kudos to you for your wonderful contribution to internet poetry :)

**Comment by thundercomb** [comment]
Thanks @javogel, I'm pleased that poetrydb is useful to you.

**Comment by thundercomb** [comment]
Hi @javogel 

In case this is still relevant, there is now an API call to limit the number of poems returned.
You can use the `poemcount` input field and corresponding search field.

For example, to return only the first Shakespeare sonnet found:

https://poetrydb.org/author,title,poemcount/Shakespeare;Sonnet;1

This returns:
```
[
  {
    "title": "Sonnet 1: From fairest creatures we desire increase",
    "author": "William Shakespeare",
    "lines": [
      "From fairest creatures we desire increase,",
      "That thereby beauty's rose might never die,",
      "But as the riper should by time decease,",
      "His tender heir might bear his memory:",
      "But thou contracted to thine own bright eyes,",
      "Feed'st thy light's flame with self-substantial fuel,",
      "Making a famine where abundance lies,",
      "Thy self thy foe, to thy sweet self too cruel:",
      "Thou that art now the world's fresh ornament,",
      "And only herald to the gaudy spring,",
      "Within thine own bud buriest thy content,",
      "And tender churl mak'st waste in niggarding:",
      "  Pity the world, or else this glutton be,",
      "  To eat the world's due, by the grave and thee."
    ],
    "linecount": "14"
  }
]
```
Or, to return the first five Shakespeare sonnets' titles:

https://poetrydb.org/author,title,poemcount/Shakespeare;Sonnet;5/title

This returns:
```
[
  {
    "title": "Sonnet 1: From fairest creatures we desire increase"
  },
  {
    "title": "Sonnet 2: When forty winters shall besiege thy brow"
  },
  {
    "title": "Sonnet 3: Look in thy glass and tell the face thou viewest"
  },
  {
    "title": "Sonnet 4: Unthrifty loveliness, why dost thou spend"
  },
  {
    "title": "Sonnet 5: Those hours, that with gentle work did frame"
  }
]
```
