### ISSUE TITLE
What is the size of PoetryDB?

### ISSUE THREAD

**Issue by heronhaye** [thundercomb/poetrydb#8]
Are there statistics on how many poems and poets there are in this database?

**Comment by thundercomb** [comment]
No official statistics, but since the numbers change as new poems are added the most reliable way is a dynamic calculation, for example in ruby:

```ruby
require 'httparty'

authors = HTTParty.get("http://poetrydb.org/authors")
puts "authors: #{authors['authors'].length}"

authors['authors'].each do |author|
  encoded_url = URI.encode("http://poetrydb.org/author/#{author}/title")
  titles = HTTParty.get(URI.parse(encoded_url))
  puts "#{author} : #{titles.length}"
end
```

**Comment by thundercomb** [comment]
As of this date there are **2787 poems** by **129 poets**.

The above code snippet breaks it down further, showing how many poems per poet.

**Comment by thundercomb** [comment]
This issue will be closed but if there are any further questions on this topic feel free to ask.
