### ISSUE TITLE
Correct linecount causes 404

### ISSUE THREAD

**Issue by ogand-anton** [thundercomb/poetrydb#9]
The following request returns a poem that is 200 lines long (as indicated by its return linecount):
_http://poetrydb.org/author,title/Algernon%20Charles%20Swinburne;Hymn%20Of%20Man/all.json_

However, when I make the request below including the linecount as a search term, a 404 is returned:
_http://poetrydb.org/author,title,linecount/Algernon%20Charles%20Swinburne;Hymn%20Of%20Man;200/all.json_

Any ideas?

**Comment by thundercomb** [comment]
Hi Anton, thanks for reporting - I agree that doesn't look right. There are some quirks related to linecount, but I'll have to dig into it when I have a bit of time to clarify the problem.

**Comment by ogand-anton** [comment]
That's OK. I can work around it. I wonder if it has anything to do with titles with spaces. 

Really appreciate this API, btw.

**Comment by thundercomb** [comment]
Glad it's useful to you! 

Thanks for the feedback, when I get a chance I'll dig into it a bit.

**Comment by thundercomb** [comment]
There have been updates to the way linecount works, and this now works as expected. 
Let me know if you have any further queries about this.
